### ISSUE TITLE
InputRequired doesn't accept 0 as valid

### ISSUE THREAD

**Issue by Grieverheart** [wtforms/wtforms#100]
Hello,

I have a form that looks like this,

    class VoteForm(Form):
        article_id = IntegerField('article_id', [validators.DataRequired()])
        vote_type  = IntegerField('vote_type', [validators.InputRequired(), validators.NumberRange(min = 0, max = 1)])

and create the form with,

    form = VoteForm(data = request.json_body)

`request.json_body` is the dictionary `{u'article_id': 1, u'vote_type': 0}`.

I would expect that the value 0 is fine with `InputRequired` but it seems it is not.

**Comment by warvariuc** [comment]
Why this issue was closed and how to handle it? I have
```
class MyForm(wtforms.Form):
    hour = wtforms.IntegerField(validators=[validators.InputRequired(), validators.NumberRange(0, 23)])
```
and when I pass `0` as `hour` validation fails...
Input is present so I don't expect `InputRequired()` to comlain.

**Comment by wilbertom** [comment]
Hey @warvariuc I don't have time to confirm that my solution will work for you but here is my fix. At least I think it was what fixed, it's been so long:

```python

class CorrectInputRequired(DataRequired):

    def __call__(self, form, field):
        if field.data is None or isinstance(field.data, string_types) and not field.data.strip():
            if self.message is None:
                message = field.gettext('This field is required.')
            else:
                message = self.message

            field.errors[:] = []
            raise StopValidation(message)


```
@JohnLZeller you're right. I should of read it better.

**Comment by wilbertom** [comment]
I guess it should be named `CorrectDataRequired`, also string_types comes from:
`from wtforms.compat import string_types`.

**Comment by warvariuc** [comment]
Hi @wilbertom, I've read you diff, but what bothers me, why it's not in the core. Is this solution bad?

**Comment by wilbertom** [comment]
@warvariuc if I were to guess I would say backwards compatibility. It's worked fine for me so far. The only downside I see to it is that it repeats a lot of code from `DataRequired`. You can also try the documented `InputRequired` as John mentioned.

https://github.com/wtforms/wtforms/blob/master/wtforms/validators.py#L185

**Comment by squfrans** [comment]
i can enter `0` with `InputRequired`, it only checks the presence of `raw_data`

(https://github.com/wtforms/wtforms/blob/master/wtforms/validators.py#L228)

**Comment by joyzhang15** [comment]
Why this issue is closed. Any solution offered?

**Comment by ycz0926** [comment]
why close this issue?
the problem is still exist, i have to change the field‘s attribute to OPtional() to avoid the error .....

**Comment by emin63** [comment]
First, I love WTForms. Great package.

I agree with the previous comment, this seems like a bug to me caused by the code using a check of the form `if not XXX` when it should be saying `if (XXX != 0 and not XXX)`.

If backwards compatibility is the issue, you could allow an optional argument to DataRequired or InputRequired to use the suggested behavior.

Are you busy and waiting for someone to submit a pull request or are we confused about this?

Thanks.

**Comment by josemonteiro** [comment]
Also having this issue: `FloatField('field', [InputRequired(), NumberRange(min=0)])` fails when the input is `0`.

**Comment by boompig** [comment]
I believe this issue should be reopened. It is not at all intuitive that `InputRequired` validator should fail on `BooleanField` when the value is False, since `InputRequired` specifically tests for whether a value is specified rather than truthiness. This is especially annoying when building APIs.

Yes, there is a workaround. Nevertheless, `InputRequired` is **broken** according to its own spec. At the very least the documentation should reflect this fact. However, the change should just be merged into mainline.

To address backwards compatibility, just bump the major version to indicate a breaking change.

**Comment by MattKleinsmith** [comment]
Relying on `NumberRange` to make the field a required field worked for me. Removed InputRequired / DataRequired:

Replace:

`price = FloatField("Price", validators=[DataRequired(), NumberRange(min=0)])`

With:

`price = FloatField("Price", validators=[NumberRange(min=0)])`

**Comment by azmeuk** [comment]
Referencing this issue as yet another duplicate of #402
