### ISSUE TITLE
StringField default value does not work

### ISSUE THREAD

**Issue by hector** [wtforms/wtforms#225]
When setting a default value to a StringField it will not use this default value in case `formdata` has been provided. The problem comes from this [line](https://github.com/wtforms/wtforms/blob/master/wtforms/fields/core.py#L530)

```python
class StringField(Field):
    """
    This field is the base for most of the more complicated fields, and
    represents an ``<input type="text">``.
    """
    widget = widgets.TextInput()

    def process_formdata(self, valuelist):
        if valuelist:
            self.data = valuelist[0]
        else:
            self.data = '' # HERE THE DEFAULT VALUE IS OVERWRITTEN

    def _value(self):
        return text_type(self.data) if self.data is not None else ''
```

which overwrites the default value.

**Comment by hector** [comment]
Probably this is enough to solve the problem:

```python
def process_formdata(self, valuelist):
        if valuelist:
            self.data = valuelist[0]
        elif self.data is None:
            self.data = ''
```

Anyway, why does the StringField set an empty string to data, couldn't it just use the parent's class Field.process_formdata method.

**Comment by hector** [comment]
Anyone there?

**Comment by crast** [comment]
This is intentional behaviour for wtforms 2.x

It may work differently or be configurable in wtforms 3.x... but this option comes at the cost of security and it will be really clear to the user when they make that choice in wtforms 3

See this FAQ entry: http://wtforms.readthedocs.org/en/latest/faq.html#why-does-blank-input-not-go-back-to-the-default-value

**Comment by hector** [comment]
I see, thank you!
