### ISSUE TITLE
Select field dynamic field documentation is wrong

### ISSUE THREAD

**Issue by ataber** [wtforms/wtforms#235]
The [code example about the "Select field with dynamic choice values"](https://wtforms.readthedocs.org/en/latest/fields.html#wtforms.fields.SelectField) is not working for me on the latest WTForms. When I don't pass in any choices to the `SelectField` constructor, I get a `TypeError: 'NoneType' object is not iterable` [here](https://github.com/wtforms/wtforms/blob/1ea78bbe2668b17c9dbb1c195c89e02a26666483/wtforms/fields/core.py#L451). Furthermore, if I do pass in choices to the SelectField constructor, and then attempt to set them later, nothing happens. Interestingly, if I write `MyForm.select_field.choices += new_choices`, then the select_field displays the new choices. Please correct the documentation to address this example. Thanks!

**Comment by crast** [comment]
nope!

**Comment by ataber** [comment]
Where am I misunderstanding? Am I not implementing the example correctly? Can I give you further information?

**Comment by crast** [comment]
Well, there's a couple of problems here:

1. This isn't a support forum, this is an issue/feature request tracker, and this ticket sort of straddles the line between support request and issue because you ask to fix the documentation but haven't clearly identified the issue beyond "doesn't work for me" and then follow it up with asking what you're not getting - A better place to ask for help is http://stackoverflow.com
2. You didn't give enough context (code sample, the form you're using, reproducible result) to show there is clearly an issue you found, nor if this was a support forum, enough information for someone to help you.
3. The issue you did identify is an intentional one - There are two ways to specify choices, and if you do neither you will get a traceback, this is to force you to specify it at least one way.

Furthermore, not only has that aspect of WTForms and the documentation been virtually unchanged in almost 8 years without anyone having a complaint about it; it's easily proven to work in the python interpreter:

```python
>>> from wtforms import *
>>> class MyForm(Form):
...    age = SelectField('Age', choices=[(x, x) for x in range(1,10)], coerce=int)
...    state = SelectField('State')
... 
>>> class obj:
...    age = 9
...    state = 'BD'
... 
>>> def view():
...    form = MyForm(obj=obj)
...    form.state.choices = [('AK', 'Alaska'), ('NY', 'New York'), ('CO', 'Colorado')]
...    assert not form.validate()
...    form.state.data = 'NY'
...    assert form.validate()
...    print form.state()
...    print form.age()
... 
>>> view()
<select id="state" name="state"><option value="AK">Alaska</option><option selected value="NY">New York</option><option value="CO">Colorado</option></select>
<select id="age" name="age"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option selected value="9">9</option></select>
```

The last thing, is mostly an attitude thing had me reject the ticket; I would encourage you to give things a shot first, and the simplicity of WTForms makes it really easy to [play with in the interpeter](http://wtforms.readthedocs.org/en/latest/crash_course.html#exploring-in-the-console). Our philosophy is to make really simple interactions that you can build on, and [encourage you to mess around to find your way](http://wtforms.readthedocs.org/en/latest/specific_problems.html#prelude-poke-it-with-a-stick
)

**Comment by jillsthebest** [comment]
Holy God.. talk about an ego issue 'crast'... more like 'crass' :P   I'm running into the same issue while 'messing around to find' my way and 'playing with in the interpreter'. The problem with your crappy working example is that it doesn't address the situation ataber referred to with dynamic choices and your attitude about his attitude is so unprofessional that you seriously deserver a lashing :D
