### ISSUE TITLE
Error when validating FileField in Pyramid

### ISSUE THREAD

**Issue by J20S** [wtforms/wtforms#296]
Hi,

I am trying to add "required" validation on FileField in Pyramid.

When I don't provide any file and submit the form, it works fine by providing "The field is required" message. However, when I actually choose a file and submit the form, I am getting errors. (Please see stacktrace at the end)

The following is the minimal code to reproduce the error.

Pyramid view and Form:

```python
class File(Form):
    file = FileField('Upload a file', validators=[required()])


@view_config(route_name='upload', renderer='templates/file.pt')
def file_view(request):
    file = File(request.POST)
    if request.method == 'POST' and file.validate():
        return render_to_response('templates/success.pt',
                                  {},
                                  request=request)
    return {'form': file}
```

And chameleon template:

```html
<!DOCTYPE HTML>
<html lang="en">
<body>
    <form method="POST" enctype="multipart/form-data" accept-charset="utf-8">
        <span tal:repeat="field form">
            ${field.label} ${field()}
            <span class="error" tal:repeat="error field.errors">
                <span>${error}</span>
            </span>
            <br><br>
        </span>
        <input type="submit" value="submit">
    </form>
</body>
</html>
```

The error I am getting is the following:

```pytb
    if request.method == 'POST' and file.validate():
  File "/home/james/venv/lib/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/james/venv/lib/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/james/venv/lib/python3.5/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/james/venv/lib/python3.5/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/james/venv/lib/python3.5/site-packages/wtforms/validators.py", line 201, in __call__
    if not field.data or isinstance(field.data, string_types) and not field.data.strip():
  File "/usr/lib/python3.5/cgi.py", line 661, in __bool__
    raise TypeError("Cannot be converted to bool.")
TypeError: Cannot be converted to bool.
```

Any help is appreciated!

**Comment by J20S** [comment]
Just add to above,
I have tried both DataRequired and InputRequired, neither of them works.

**Comment by nek4life** [comment]
I'm running into the same issue as well. In the case of InputRequired it looks like this is the offending line.

`
if not field.raw_data or not field.raw_data[0]:
`

It breaks on `not field_raw_data[0]` 

WebOb puts a cgi.FieldStorage() object directly on req.POST (I'm not a huge fan of this behavior, but that's how it is) and it seems that it does not know how to represent itself as a bool. I'm not sure what else is expected to be there when used with other frameworks so I'm not sure what condition would be safe to check here in order to make it work.

I'm currently using the following libraries.

pyramid==1.8.3
WebOb==1.7.2 <brought in by Pyramid>
WTForms==2.1

I did not look into DataRequired, but that is also exhibiting the same behavior for me. I thought input required would be the proper validator to use in the case of a file field.

Any further insights would be greatly appreciated.

**Comment by nek4life** [comment]
@J20S as a workaround instead of using the validator I was able to add a custom validator to the form object.

```python
class UploadForm(Form):
    title = StringField(validators=[InputRequired()])
    description = TextAreaField()
    image = FileField()

    def validate_image(self, field):
        if not isinstance(field.data, cgi.FieldStorage):
            raise ValidationError("This field is required.")
```

**Comment by davidism** [comment]
That's strange that `cgi.FieldStorage` doesn't allow using it as a bool. I'm not familiar with Pyramid. Can something in `wtforms.utils.WebobInputWrapper` be tweaked to fix this?

**Comment by nek4life** [comment]
It looks like `cgi.FieldStorage` does have __bool__ defined, but it seems to be failing because of the self.list attribute. 

```python
def __bool__(self):
    if self.list is None:
        raise TypeError("Cannot be converted to bool.")
    return bool(self.list)
```

**Comment by davidism** [comment]
Why is `self.list` none? That seems like the first place to investigate.

**Comment by nek4life** [comment]
I read through cgi.FieldStorage a bit and it looks like list is only set if there are multiple values parsed by the FieldStorage class. If there is only one value then list is set to None. It looks like they overloaded things like __contains__ and __bool__ if the object is a list. Seems weird, but I know that is quite an old module in the standard library.

Looks like Werkzeug also uses FieldStorage objects, albeit on request.files instead of on request.POST, so I'm wondering what the difference is. Does wtforms treat .files separately?

**Comment by davidism** [comment]
No, Flask-WTF combines `request.form` and `request.files`. But `FileStorage` is a different class than `FieldStorage`.

**Comment by nek4life** [comment]
You're right. It's getting late and I read that too quickly. Right now with or without wtforms you need to do something like isinstance(field.data, cgi.FieldStorage) to test for the existence of a cgi.FieldStorage object. Using a boolean operator does not work with a single field parsed by cgi.FieldStorage.

I'm going to pick this back up tomorrow to see what options exist to add some kind of compatibility shim. I'll also take a look at Flask-WTF, perhaps if there's not a solve in `wtforms.utils.WebobInputWrapper` writing something similar might be the way to go.

Thanks for your assistance. I really appreciate it.

**Comment by ftm** [comment]
Was it decided that this was not an issue with WTForms?
