### ISSUE TITLE
SelectMultiple defaults cannot be overridden

### ISSUE THREAD

**Issue by mattouille** [wtforms/wtforms#371]
This could have to do with Flask-WTForms

In my views:
```
    form = EditUserForm(request.form)
    form.tenants.choices = [(tenant.id, tenant.name) for tenant in Tenant.query.all()]
    form.tenants.default = ['1']
```

Choices is overriden from here, default is not.

From my forms.py
```
    tenants = SelectMultipleField(coerce=int, default=[], validators=[Optional()])
```

The only thing that seems to effect the defaults is if I put default directly into the class instantiation in forms.py

**Comment by davidism** [comment]
See [Setting default value after initialization in SelectField](https://stackoverflow.com/q/36157362/400617). Creating an instance of the form binds the data, setting the default after that is meaningless. Instead, pass the default as an argument. Choices is different because that's validation, not binding, which only happens when you call `validate`.
