### ISSUE TITLE
valid email address deemed invalid

### ISSUE THREAD

**Issue by janwijbrand** [wtforms/wtforms#384]
This issue was initially reported here: https://github.com/pypa/warehouse/issues/3733. There it was suggested to report the issue here as the issue apparently originates from pypa/warehouse's dependency on wtforms.

When trying to add an additional email address to my account on https://pypi.org/, the email address is rejected. This email address however /is/ valid. The domain for the email address is `n--tree.net`. I guess the validator trips over the (admittedly uncommon) double dash in it. Hopefully this can be resolved.

**Comment by davidism** [comment]
I really just want to remove this validator. It will never be correct.

Can you try with the master version, and check the other PRs? It may have been fixed by a previous PR, but I don't have a lot of time to check right now. A new release of WTForms is on my todo list, but I probably won't get to it soon.
