### ISSUE TITLE
InputRequired validator doesn't work for FieldList

### ISSUE THREAD

**Issue by nathan-steyer** [wtforms/wtforms#432]
The `InputRequired` validator checks the `raw_data` attribute of the field to determine if input was submitted, but this attribute is never populated for `FieldList`s. This causes validation to fail even when at least one valid list item is submitted.

This appears to be the same problem mentioned in [#220](https://github.com/wtforms/wtforms/issues/220).

I think the validator could easily be modified to conditionally check the `entries` attribute for `FieldList`s, but I'm not sure if that is the preferred solution for this bug.

**Comment by davidism** [comment]
If you need to validate that all fields in a ListField are filled, that's a good case for a custom validator. And who's to say that "required" means "all fields have data" rather than "at least one field has data"? I don't want to add behavior for specific fields to generic validators.

However, you'd probably be better served by adding the validator to the wrapped field instead. (This is off the top of my head, might need adjustment.)

```python
items = FieldList(StringField(validators=[DataRequired()]))
```

**Comment by nathan-steyer** [comment]
I only want to validate that there is at least one entry in the list. In my opinion, that is the only reasonable interpretation of "required" when it comes to a `FieldList`.

It should at least be clarified somewhere that the `InputRequired` validator does not work for `FieldList`s because I've seen it mistakenly used in a few places now, including in the mongoengine model-to-form converter in Flask-Admin.

**Comment by alanhamlett** [comment]
Just to chime in, my interpretation of required for `FieldList` is that an empty list was provided.
