### ISSUE TITLE
Checking only first string symbol

### ISSUE THREAD

**Issue by dmytrostriletskyi** [wtforms/wtforms#448]
While [checking](https://github.com/wtforms/wtforms/blob/master/src/wtforms/fields/core.py#L672) first symbol of the string value that would be converted to integer after validation, there will be no errors if validate the following argument:

```python
class Form(Form):

    id_ = IntegerField('Parent directory identifier')


form = Form({
    'id_: '2njadhuaibsd',
})
print(form.validate(), form.errors) . # True {}
```

**Comment by antishamik** [comment]
#451 I think it solves this problem

**Comment by ftm** [comment]
I'm not sure that #451 will solve the issue. The example you present deals with `formdata`, whereas the pull request deals with `process_data` so it shouldn't make a difference.

Additionally, I cannot replicate the error you describe.

```python
from wtforms.fields.core import IntegerField
from wtforms.form import Form

class Form(Form):
    id_ = IntegerField('Parent directory identifier')

form = Form({
    "id_": "2njadhuaibsd",
})

print(form.validate(), form.errors)
```

This gives me a `TypeError: formdata should be a multidict-type wrapper that supports the 'getlist' method ` on the dict being passed into `F` which is expected behaviour. Passing data into `formdata` in this way requires the use of a [MultiDict](https://werkzeug.palletsprojects.com/en/0.16.x/datastructures/#werkzeug.datastructures.MultiDict)-like structure

**Comment by azmeuk** [comment]
I confirm #451 fixes this issue.

```python
>>> from wtforms import Form, IntegerField                                                                                                                                                      
>>> class F(Form): 
...    foo = IntegerField('foobar')                                                                                                                                                             
>>> form = F(foo='2njadhuaibsd')
>>> form.validate(), form.errors                                                                                                                                                                
```
With #451:  `(False, {'foo': ['Not a valid integer value']})`
Without: `(True, {})`
