### ISSUE TITLE
FieldList id attribute

### ISSUE THREAD

**Issue by Berrayti** [wtforms/wtforms#473]
Hi guys,

I'm using FieldList along with a FormField like this 
```python
class OneLineForm(FlaskForm):
    id = HiddenField('id')
    name = StringField("Name", validators=[DataRequired()])

class AllLinesForm(FlaskForm):
    lines = FieldList(FormField(OneLineForm), min_entries=1
```

In my view function, I prepopulate the form with data from a SQLAlchemy model like this

```python
@app.route('test')
def test_route():
    db_lines = Line.query.all()
    form = AllLinesForm(lines=db_lines)
```

In my jijna file, I have this : 

```jinja
{% for line in form.lines %}
    {{ line.id }}
    {{ render_field(line.name) }}
{% endfor %}
```

The problem is that I don't get the hidden field markup with the value from the Database, but I get **line-0** **line-1** .... It's like treating that id field as the id of the field and not the one from the DB.

I hope my problem is understable.

Thank you

**Comment by ftm** [comment]
Apologies for the delay in replying, you are correct in your suspicion that `line.id` is returning the `id` attribute of the `FormField` instead of the `id` attribute of your `OneLineForm`

Since `line` is referring to the instance of `FormField`, one can access the underlying form with `line.form`. So you can do `line.form.id` to access the ID field.

**Comment by ftm** [comment]
Please use Stack Overflow for questions about your own code. This issues board is for issues relating to WTForms itself. Be sure to include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).
