### ISSUE TITLE
[Feature] File size validation

### ISSUE THREAD

**Issue by avinash-bhosale** [wtforms/wtforms#515]
First time I post an Issue/Feature request. Please excuse me and let me know where I went wrong.

WTForms and flask-wtf provide excellent and easy to use validations. I searched for the file size validator, but i didn't succeed. There should be validator for file size checker and returning the errors

**Comment by ftm** [comment]
WTForms itself does not deal with any file handling capability, including anything to do with file sizes, that's why we do not have a file size validator.

I would point you to the Flask documentation [here](https://flask.palletsprojects.com/en/1.1.x/patterns/fileuploads/#improving-uploads) for some information about limiting maximum file upload sizes however it may not be suitable for your particular goal.
