### ISSUE TITLE
RegEx fails on integer fields

### ISSUE THREAD

**Issue by technikamateur** [wtforms/wtforms#519]
Hi,
I am trying to match an integer input against the linux file permission. So I created an integer field like the following:
`    create_mask = IntegerField("File Mask", [validators.Optional(),
                                              validators.Regexp('^[0-7]{4}$', message="This is not a valid value!")],
                               render_kw={"placeholder": "0600"})`

But with the input `55` (which is a not allowed input), a Type Error is thrown:

`  File "/usr/local/lib/python3.6/dist-packages/wtforms/validators.py", line 273, in __call__
    match = self.regex.match(field.data or '')
TypeError: expected string or bytes-like object`

Is it not possible to check a regex against a string or am I doing something completly wrong?

Cheers,
Daniel

**Comment by ftm** [comment]
Regular expressions are only really designed for use with strings. The error you are getting is because the `IntegerField` will be coercing the value into an `int` then when the regex gets applied you get the `TypeError`.

Since you are enforcing the format of the field anyway with the regex I would recommend just using a TextField.

I will close this issue for now but if there is a larger issue I'll be happy for it to be reopened.
