### ISSUE TITLE
Form errors property isn't idempotent

### ISSUE THREAD

**Issue by jwag956** [wtforms/wtforms#522]
The 'errors' property in BaseForm isn't idempotent. In particular - if you iterate over a forms attributes using e.g. inspect.getmembers - this will cause 'errors' to change from 'None' to dict({}). And so it won't be updated if any fields add/incur errors later in processing.

At a minimum, it should treat 'None' and empty dir the same. But I don't understand why it doesn't re-calc the errors every time?

**Comment by azmeuk** [comment]
Hello. Thank you for reporting this issue.
Could you please provide us a reproducible piece of code illustrating the problem you are describing?

**Comment by jwag956** [comment]
Will do - thanks for looking into this - will take a few days to context switch that back in :-)

**Comment by jwag956** [comment]
Ok - really really simple:

```
from wtforms import Form, StringField, validators
from werkzeug.datastructures import MultiDict


class MyForm(Form):
    username = StringField(validators=[validators.DataRequired()])

    def validate(self):
        if not super(MyForm, self).validate():
            return False
        if not self.errors:
            if len(self.username.data.strip()) < 3:
                self.username.errors.append("Too Short")
        return True


form = MyForm(MultiDict(dict(username="a")))
form.validate()
print(f"Form errors: {form.errors}")
print(f"Username errors: {form.username.errors}")
```

Result:
Form errors: {}
Username errors: ['Too Short']

Expected:
Form errors:{"username": ["Too Short"]

It is really just this definition:

```
    @property
    def errors(self):
        if self._errors is None:
            self._errors = dict((name, f.errors) for name, f in iteritems(self._fields) if f.errors)
        return self._errors
```

Not clear why it is 'caching' errors rather than just recomputing them.....

**Comment by davidism** [comment]
It's caching for a few reasons. First, `form.errors` needs to be writable so you can add form-level errors. For example, from what I remember of Django, it does this by assigning to `form.errors['_form']` or something like that. Second, computing this on every access is expensive, and that's not clear to the user, who may access this multiple times.

I'm not convinced by the example you've shown. Why do you need to know if there are errors in the form before adding an error for a specific field? I'd expect there to be a better way to deal with your case rather than changing the behavior of `form.errors`.
