### ISSUE TITLE
Python 3.7 PyPi

### ISSUE THREAD

**Issue by Tomazz** [wtforms/wtforms#527]
Hi Guys,

I see you've got a PR with python 3.8 tests, so assuming that 3.7 should be supported now (saw commits with 3.7 tests from 5 months back). Did you perhaps forgot to include the 3.7 support on PyPI? You have python versions listed up until 3.6 there.

**Comment by whb07** [comment]
So 3.7 tests and the checks for Travis got added recently. As far as the Pypi package repo, it appears that you're correct. I'll be adding a 3.7 flag to Pypi unless you would like to do it?

**Comment by ftm** [comment]
As shown [here](https://github.com/wtforms/wtforms/blob/23f730a9cfca478f01fda2b38fde17ad56e9a83d/setup.py#L93), Python 3.7 is listed as a supported Python version for use with PyPI.

The issue is that the latest version available on PyPI is over a year old and so no changes since then (including adding Python 3.7 support) have been published yet. As soon as a new version is published the Python 3.7 tag should appear on there.
