### ISSUE TITLE
2.2.1 fix for default value in StringField breaks nullable fields

### ISSUE THREAD

**Issue by jwag956** [wtforms/wtforms#562]
There is a long discussion in: #401 
however the fix - which means that the value for the StringField can NEVER be None is a real problem. While in python None and '' (empty string) are mostly the same - this is definitely not true for DBs which treat those 2 concepts completely differently.

What this means for example is that current StringField can't be used for a Unique/Nullable field in the DB.

I don't quite understand the rationale for the else clause here:
```python
        if valuelist:
            self.data = valuelist[0]
        elif self.data is None:
            self.data = ''

```

**Comment by davidism** [comment]
I'm not clear what's being reported here, and it's been years since I last looked at this behavior. If I remember correctly and have read the existing threads (there's more than the one you linked) correctly, in 3.0, the value will be `None`, which sounds like what you're asking for. In 2.2, I had to find a middle ground between even older incorrect behavior and not breaking everything in the first release in years.
