### ISSUE TITLE
Rework the WTForms logo

### ISSUE THREAD

**Issue by azmeuk** [wtforms/wtforms#569]
We have this logo for the wtforms group:

![logo](https://avatars2.githubusercontent.com/u/4740084?s=200&v=4)

And we have this logo for the documentation:

![logo](https://wtforms.readthedocs.io/en/stable/_static/wtforms.png)

Both are in poor resolution. We should probably make them svgs.

Any suggestions or help is welcomed!

**Comment by davidism** [comment]
This might sound a little silly, but I've never really liked the logo. I get that the speech bubble with angry symbols is a play on WTF, but that's not really relevant to what the library is at all.

Maybe something more understated, I'll try some ASCII art:

```
 ------------   ----
[ WTForms |  ] [ ?! ]
 ------------   ----
```

Pretend the first box is a text intput with the cursor at the end, and the second box is a submit button.

**Comment by sblondon** [comment]
I guess you think about something like these:

![wtforms](https://user-images.githubusercontent.com/1708780/95611533-407def80-0a62-11eb-981b-88c057f0adee.png)

(They are screenshots from basic html (first logo) and bootstrap theme (second logo).)

I don't think it's a good idea to keep the input text because it forces the logo to be rectangular and it will not be easy to modify it for every needs. I suggest to replace the current speech bubble by the submit button, without 'WTForms' inside the input text. In such case, the  'WTForms' name could be more or less like today. So it will be possible to have several layout like in azmeuk's post. It could be even the button only for smaller area.

**Comment by funelie** [comment]
Hey there ! I've made a few proposals on this matter. What do you think ?
![Frame 7](https://user-images.githubusercontent.com/19359364/116413884-4b4e7500-a838-11eb-83b0-704ebb3454b0.png)
![Frame 1](https://user-images.githubusercontent.com/19359364/116413888-4be70b80-a838-11eb-8c21-2c38265910d3.png)
![Frame 2](https://user-images.githubusercontent.com/19359364/116413891-4be70b80-a838-11eb-8434-e96b1258bb43.png)
![Frame 3](https://user-images.githubusercontent.com/19359364/116413894-4c7fa200-a838-11eb-8abb-904c9f3cf1c2.png)

**Comment by azmeuk** [comment]
Yep. The first one is my favorite too.

**Comment by davidism** [comment]
Can you make a PR with these in a new `artwork` folder? You can also add them to the docs, or we can add them after that.

**Comment by azmeuk** [comment]
Are all the logos needed? Maybe we can select one and use it everywhere?

**Comment by davidism** [comment]
Not sure how it will look in the docs yet, I was thinking at least the second one, left section only, might be easier for the sidebar.

**Comment by azmeuk** [comment]
This looks pretty good to me!

![Screenshot_2021-04-28 Solving Specific Problems — WTForms Documentation (3 0 x)](https://user-images.githubusercontent.com/60163/116418711-ada97480-a83c-11eb-8f63-6807ecb9fe00.png)
