### ISSUE TITLE
SelectField choices can no longer be set to `dict_values` as they are not indexable

### ISSUE THREAD

**Issue by jon-brenner** [wtforms/wtforms#644]
This change breaks the ability to set `choices` on a SelectField to a `dict_values` object as they are not indexable:
https://github.com/wtforms/wtforms/pull/526/files#diff-499875f3f88b585a74b57a09d789bbfcR525

```
field = SelectField()
choices_dict = {'name1': ('v1', 'v2), 'name2': ('v3', 'v4')}
field.choices = choices_dict.values()
```

Obviously this applies to any iterable type that is not indexable e.g. `dict_items`, `dict_keys`, etc

**Comment by davidism** [comment]
Essentially the same as #588 and #339. The problem is, `dict_values`, etc. are not constant (and until very recently, had no defined order). If you were expecting `dict_values` to reflect the updated underlying dict, that expectation was already broken because select field would copy the data.

Pass `list(choices_dict.values())` if you need that data structure for your project.

**Comment by jon-brenner** [comment]
> Essentially the same as #588 and #339. The problem is, `dict_values`, etc. are not constant (and until very recently, had no defined order). If you were expecting `dict_values` to reflect the updated underlying dict, that expectation was already broken because select field would copy the data.
> 
> Pass `list(choices_dict.values())` if you need that data structure for your project.

I think this is a reasonable expectation, but the library should provide an error message stating this reasoning at the very least.
