### ISSUE TITLE
SelectField doesn't coerce in pre_validate

### ISSUE THREAD

**Issue by RR2DO2** [wtforms/wtforms#67]
I ran into this when I had a SelectField setup with a coerce of uuid.UUID. Because SelectField.pre_validate doesn't coerce the value from the choices, the validation failed. Similar to iter_choices, pre_validate should likely coerce on the values, something along these lines:

``` python
    def pre_validate(self, form):
        for v, _ in self.choices:
            if self.data == self.coerce(v):
                break
        else:
            raise ValueError(self.gettext('Not a valid choice'))
```

The other option would be to specify that the first part of choices should always be coerced already, but the rest of the code doesn't appear to assume that.

**Comment by dkasak** [comment]
Why is this being ignored? @RR2DO2 is correct that the `choices` values are coerced in `iter_choices` while @crast says they should already be coerced there.

I think this is a mistake due to similar naming of variables in `iter_choices` and `process_data`:

    def iter_choices(self):
        for value, label in self.choices:
            yield (value, label, self.coerce(value) == self.data)

    def process_data(self, value):
        try:
            self.data = self.coerce(value)
        except (ValueError, TypeError):
            self.data = None

Both are named `value`, but one refers to the input while the other refers to the value stored in `choices`. The latter got mistakenly coerced because of this. Because of this, it only works if both the values in `choices` and their string representations can be coerced to equal objects with the same function (as is the case for `int`, for instance, since `int(0) == int("0")`).

I also see there are at least two pull requests related to this. Please fix this.
