### ISSUE TITLE
Incorrect docstring?

### ISSUE THREAD

**Issue by Nicholas-Read** [wtforms/wtforms#811]
Barely a bug at all, but the docstring describes iter_choices [here ](https://github.com/wtforms/wtforms/blob/master/src/wtforms/widgets/core.py#L335) is out of sync with the code [just below](https://github.com/wtforms/wtforms/blob/master/src/wtforms/widgets/core.py#L365), which unpacks a tuple of length 4!

Also on the core class [here](https://github.com/wtforms/wtforms/blob/master/src/wtforms/fields/choices.py#L33)!

Thanks for the great library!

**Comment by aminalaee** [comment]
Yeah I think this wasn't a backwards-compatible change and already broke some code: https://github.com/aminalaee/sqladmin/pull/644

**Comment by davidism** [comment]
Sorry, I thought you were saying that multiple docs were out of sync, you actually were saying that the docs were out of sync with the code.

**Comment by aminalaee** [comment]
Yeah I think that's the initial discussion, but it also breaks the code. I guess it's related to: https://github.com/wtforms/wtforms/pull/739

**Comment by azmeuk** [comment]
I have fixed the examples and added a message in the changelog about the compatibility break.

**Comment by azmeuk** [comment]
About your point on old unmaintained projects breaking, and people having to spend time to update their code, well there is a tradeoff to be made:
People ask for bugfixes and features in wtforms, that leads to refactoring, that sometimes leads to compatibility breakages. Keeping the old API puts the maintenance burden on the wtforms maintainers instead of the maintainers of projects using wtforms.

I would not be against making render_kw optional for now, with a deprecation warning for a definitive removal in the next release. This way we can share the burden.

Are you interested in opening a PR?

**Comment by guidoiaquinti** [comment]
> About your point on old unmaintained projects breaking, and people having to spend time to update their code, well there is a tradeoff to be made: People ask for bugfixes and features in wtforms, that leads to refactoring, that sometimes leads to compatibility breakages. Keeping the old API puts the maintenance burden on the wtforms maintainers instead of the maintainers of projects using wtforms.
> 
> I would not be against making render_kw optional for now, with a deprecation warning for a definitive removal in the next release. This way we can share the burden.
> 
> Are you interested in opening a PR?

First of all, thank you for developing such an outstanding library! I agree with your stance that breaking changes are sometimes essential. However, I'm concerned about the introduction of this breaking change within a minor release (despite I'm not sure if this project follows semantic versioning or not). In this case, by cutting a major release we would have likely avoided downstream dependencies issue.

Thank you for your time and have a good day! 🙌
